# Generated by Django 5.1.2 on 2024-10-18 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='member',
            name='birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='member',
            name='login',
            field=models.CharField(default='Morose', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='Hello123', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(default='Mor', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.CharField(default='Morse', max_length=255),
        ),
    ]
