# Generated by Django 5.1.2 on 2024-10-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_age_alter_member_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='login',
            field=models.CharField(default='login', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
