# Generated by Django 5.1.2 on 2024-10-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_account_alter_member_firstname_alter_member_lastname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
        migrations.AddField(
            model_name='member',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='member',
            name='login',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
