# Generated by Django 5.1.2 on 2024-10-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_delete_account_member_last_login_alter_member_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='birth',
        ),
    ]
