# Generated by Django 5.1.2 on 2024-10-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_groups_member_is_active_member_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user_permissions',
        ),
    ]
