# Generated by Django 5.1.2 on 2024-11-01 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_groups_member_is_active_member_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveIntegerField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('money_date', models.DateTimeField()),
                ('tab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.userprofile')),
            ],
        ),
    ]
