# Generated by Django 5.1.2 on 2024-11-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='money',
            field=models.PositiveIntegerField(),
        ),
    ]
