# Generated by Django 5.1.2 on 2024-11-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_account_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='money',
            field=models.IntegerField(default=22000),
        ),
        migrations.DeleteModel(
            name='account',
        ),
    ]
