# Generated by Django 5.1.3 on 2024-11-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0015_remove_userprofile_comment_remove_userprofile_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                default="default.jpg", null=True, upload_to="profile_images"
            ),
        ),
    ]
