# Generated by Django 5.1.3 on 2024-11-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0016_userprofile_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="age",
        ),
        migrations.AddField(
            model_name="member",
            name="email",
            field=models.EmailField(default=None, max_length=100, unique=True),
        ),
    ]
