# Generated by Django 5.1.3 on 2024-11-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0017_remove_member_age_member_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(default=True, max_length=100, unique=True),
        ),
    ]
