# Generated by Django 5.1.3 on 2024-11-12 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0018_alter_member_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="email",
        ),
    ]
