# Generated by Django 5.1.3 on 2024-11-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_remove_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='no-email@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
