# Generated by Django 5.1.3 on 2024-11-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
