# Generated by Django 5.1.3 on 2024-11-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
