# Generated by Django 5.1.3 on 2024-11-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_remove_member_email_member_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
    ]
