# Generated by Django 6.0.2 on 2026-04-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_remove_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
    ]
